In [4]:
# Lab 5 Logistic Regression Classifier
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(-tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

'''
0 0.82794
200 0.755181
400 0.726355
600 0.705179
800 0.686631
...
9600 0.492056
9800 0.491396
10000 0.490767

...

 [ 1.]
 [ 1.]
 [ 1.]]
Accuracy:  0.762846
'''


(759, 8) (759, 1)
0 0.6343239
500 0.5992263
1000 0.57324487
1500 0.55367607
2000 0.5387502
2500 0.5272108
3000 0.518167
3500 0.51098454
4000 0.5052088
4500 0.5005104
5000 0.49664792
5500 0.4934424
6000 0.49075913
6500 0.48849544
7000 0.4865725
7500 0.48492837
8000 0.48351473
8500 0.48229274
9000 0.4812312
9500 0.480305
10000 0.47949338

Hypothesis:  [[0.4145524 ]
 [0.9246203 ]
 [0.28844094]
 [0.9355513 ]
 [0.29979706]
 [0.7795712 ]
 [0.9398232 ]
 [0.59739286]
 [0.21464369]
 [0.5271233 ]
 [0.6744268 ]
 [0.18111628]
 [0.40286878]
 [0.22598878]
 [0.7805338 ]
 [0.44587773]
 [0.7516722 ]
 [0.8189086 ]
 [0.8058549 ]
 [0.5857307 ]
 [0.68384206]
 [0.09482458]
 [0.6634192 ]
 [0.6666207 ]
 [0.33425045]
 [0.9377048 ]
 [0.58051157]
 [0.64165336]
 [0.6796136 ]
 [0.47198066]
 [0.9494179 ]
 [0.8961425 ]
 [0.6211964 ]
 [0.8756715 ]
 [0.40051872]
 [0.6838272 ]
 [0.8153919 ]
 [0.6460326 ]
 [0.3966583 ]
 [0.3817725 ]
 [0.8278432 ]
 [0.1280585 ]
 [0.4318835 ]
 [0.09192789]
 [0.6061764 ]
 [0.9368956 ]
 [0.

'\n0 0.82794\n200 0.755181\n400 0.726355\n600 0.705179\n800 0.686631\n...\n9600 0.492056\n9800 0.491396\n10000 0.490767\n\n...\n\n [ 1.]\n [ 1.]\n [ 1.]]\nAccuracy:  0.762846\n'

In [5]:
# Lab 6 Softmax Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1)) #축의 이름 그 축을 따라서 더해랏! 

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))                                      #argmax로 리턴되는 값은 인덱스이다

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

'''
0 6.926112
200 0.6005015
400 0.47295815
600 0.37342924
800 0.28018373
1000 0.23280522
1200 0.21065344
1400 0.19229904
1600 0.17682323
1800 0.16359556
2000 0.15216158
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]
-------------
[[0.9311919  0.06290216 0.00590591]] [0]
-------------
[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]
 [9.3119192e-01 6.2902197e-02 5.9059085e-03]
 [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]
'''


0 10.740347
200 0.51755947
400 0.4229287
600 0.34907848
800 0.27630833
1000 0.23088129
1200 0.20952602
1400 0.19167402
1600 0.17652956
1800 0.16352652
2000 0.15224753
--------------
[[3.7315406e-03 9.9625969e-01 8.7909657e-06]] [1]
--------------
[[0.8793191  0.10902744 0.01165348]] [0]
--------------
[[1.0728419e-08 3.1383717e-04 9.9968612e-01]] [2]
--------------
[[3.7315406e-03 9.9625969e-01 8.7909657e-06]
 [8.7931907e-01 1.0902744e-01 1.1653478e-02]
 [1.0728418e-08 3.1383717e-04 9.9968612e-01]] [1 0 2]


'\n0 6.926112\n200 0.6005015\n400 0.47295815\n600 0.37342924\n800 0.28018373\n1000 0.23280522\n1200 0.21065344\n1400 0.19229904\n1600 0.17682323\n1800 0.16359556\n2000 0.15216158\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]\n-------------\n[[0.9311919  0.06290216 0.00590591]] [0]\n-------------\n[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]\n [9.3119192e-01 6.2902197e-02 5.9059085e-03]\n [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]\n'