In [2]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('happiness.csv', delimiter=',', dtype=np.float32)
np.arr1 = xy[:,1:3]
np.arr2 = xy[:,4:-2]

x_data =np.hstack([np.arr1,np.arr2])
y_data = xy[:, [3]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[1.39651 1.34951 0.66557 0.41978 0.29678]
 [1.30232 1.40223 0.62877 0.14145 0.4363 ]
 [1.32548 1.36058 0.64938 0.48357 0.34139]
 [1.459   1.33095 0.66973 0.36503 0.34699]
 [1.32629 1.32261 0.63297 0.32957 0.45811]
 [1.29025 1.31826 0.64169 0.41372 0.23351]
 [1.32944 1.28017 0.61576 0.31814 0.4761 ]
 [1.33171 1.28907 0.6598  0.43844 0.36262]
 [1.25018 1.31967 0.63938 0.42922 0.47501]
 [1.33358 1.30923 0.65124 0.35637 0.43562]
 [1.22857 1.22393 0.41319 0.07785 0.33172]
 [0.95578 1.23788 0.63376 0.10583 0.25497]
 [1.33723 1.29704 0.62433 0.18676 0.33088]
 [1.02054 0.91451 0.48181 0.21312 0.14074]
 [1.39451 1.24711 0.54604 0.1589  0.40105]
 [0.98124 1.23287 0.49049 0.17521 0.14574]
 [1.56391 1.21963 0.61583 0.37798 0.28034]
 [1.33596 1.36948 0.61777 0.28703 0.45901]
 [1.30782 1.28566 0.5845  0.2254  0.2225 ]
 [1.42727 1.12575 0.64157 0.38583 0.26428]
 [1.26637 1.28548 0.59625 0.32067 0.51912]
 [1.36011 1.08182 0.63274 0.32524 0.21542]
 [1.04424 1.25596 0.42908 0.11069 0.05841]
 [1.52186 1

In [3]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 5])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([5, 1]), name='pred1')
b = tf.Variable(tf.random_normal([1]), name='pred2')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)
    
        
        
        


Instructions for updating:
Colocations handled automatically by placer.
0 Cost: 0.395095 
Prediction:
 [[ 1.4669688 ]
 [ 1.5145688 ]
 [ 1.4041802 ]
 [ 1.5009538 ]
 [ 1.4106444 ]
 [ 1.4105699 ]
 [ 1.4033554 ]
 [ 1.3553045 ]
 [ 1.304219  ]
 [ 1.3838171 ]
 [ 1.6479139 ]
 [ 1.18465   ]
 [ 1.4947498 ]
 [ 1.2040497 ]
 [ 1.5893719 ]
 [ 1.3880339 ]
 [ 1.5914901 ]
 [ 1.4814246 ]
 [ 1.5329746 ]
 [ 1.3892429 ]
 [ 1.3662657 ]
 [ 1.3495761 ]
 [ 1.5751952 ]
 [ 1.4673672 ]
 [ 1.3632226 ]
 [ 1.5056089 ]
 [ 1.4326195 ]
 [ 1.5096884 ]
 [ 1.5694212 ]
 [ 1.5431198 ]
 [ 1.6186649 ]
 [ 1.2508582 ]
 [ 1.3151944 ]
 [ 1.2310232 ]
 [ 1.7953842 ]
 [ 1.7032932 ]
 [ 1.3780372 ]
 [ 1.6395476 ]
 [ 1.6943309 ]
 [ 1.0977292 ]
 [ 1.4540753 ]
 [ 1.208268  ]
 [ 0.9500568 ]
 [ 0.91122556]
 [ 1.8103982 ]
 [ 1.6400673 ]
 [ 1.6229776 ]
 [ 1.1484972 ]
 [ 1.6466203 ]
 [ 1.8781648 ]
 [ 0.8813283 ]
 [ 1.1567056 ]
 [ 1.1687663 ]
 [ 1.4308449 ]
 [ 1.4449768 ]
 [ 1.961731  ]
 [ 0.89097023]
 [ 1.2735996 ]
 [ 1.5698897 ]
 [ 1.5199108

400 Cost: 0.05774944 
Prediction:
 [[ 0.7393148 ]
 [ 0.78639174]
 [ 0.69833213]
 [ 0.7639143 ]
 [ 0.7134179 ]
 [ 0.70909727]
 [ 0.71562594]
 [ 0.6674105 ]
 [ 0.6364716 ]
 [ 0.6902811 ]
 [ 0.9459692 ]
 [ 0.5702071 ]
 [ 0.7785987 ]
 [ 0.6383468 ]
 [ 0.8672943 ]
 [ 0.7452    ]
 [ 0.84568113]
 [ 0.7643504 ]
 [ 0.81481653]
 [ 0.7058656 ]
 [ 0.6950959 ]
 [ 0.6853021 ]
 [ 0.8897142 ]
 [ 0.7880745 ]
 [ 0.71876234]
 [ 0.78754866]
 [ 0.79569834]
 [ 0.7869879 ]
 [ 0.8507637 ]
 [ 0.86348414]
 [ 0.9152667 ]
 [ 0.6209787 ]
 [ 0.6869213 ]
 [ 0.62258095]
 [ 1.0745103 ]
 [ 0.9670884 ]
 [ 0.7054916 ]
 [ 0.95247674]
 [ 0.9383822 ]
 [ 0.5344954 ]
 [ 0.7793518 ]
 [ 0.65861994]
 [ 0.43605953]
 [ 0.36596543]
 [ 1.0809302 ]
 [ 0.9141364 ]
 [ 0.96505344]
 [ 0.5957365 ]
 [ 0.92814267]
 [ 1.145779  ]
 [ 0.39383703]
 [ 0.6467037 ]
 [ 0.581378  ]
 [ 0.7761404 ]
 [ 0.75436914]
 [ 1.2131426 ]
 [ 0.39357972]
 [ 0.70450366]
 [ 0.8981904 ]
 [ 0.82556504]
 [ 0.69211507]
 [ 0.9306466 ]
 [ 0.86922693]
 [ 1.0317254 ]
 [ 0.

800 Cost: 0.045165177 
Prediction:
 [[ 0.7612548 ]
 [ 0.79551184]
 [ 0.7290132 ]
 [ 0.7865197 ]
 [ 0.74451137]
 [ 0.7264011 ]
 [ 0.7477992 ]
 [ 0.7034436 ]
 [ 0.6810558 ]
 [ 0.72474813]
 [ 0.91957176]
 [ 0.58365744]
 [ 0.78565407]
 [ 0.64371395]
 [ 0.86802423]
 [ 0.72843933]
 [ 0.85741997]
 [ 0.78610253]
 [ 0.8089613 ]
 [ 0.7326986 ]
 [ 0.73076093]
 [ 0.70673394]
 [ 0.8448572 ]
 [ 0.81546545]
 [ 0.7137395 ]
 [ 0.7905714 ]
 [ 0.7897246 ]
 [ 0.8235978 ]
 [ 0.830495  ]
 [ 0.8260735 ]
 [ 0.8730899 ]
 [ 0.6357393 ]
 [ 0.67386156]
 [ 0.6487254 ]
 [ 1.0333997 ]
 [ 0.92527604]
 [ 0.72927606]
 [ 0.92380536]
 [ 0.92284644]
 [ 0.55277455]
 [ 0.7739754 ]
 [ 0.64232993]
 [ 0.46339506]
 [ 0.40111244]
 [ 1.0176426 ]
 [ 0.8818629 ]
 [ 0.92860436]
 [ 0.5966568 ]
 [ 0.90639305]
 [ 1.0811807 ]
 [ 0.4200377 ]
 [ 0.6282073 ]
 [ 0.5893093 ]
 [ 0.75638103]
 [ 0.74699247]
 [ 1.1178899 ]
 [ 0.42384428]
 [ 0.68855226]
 [ 0.85877156]
 [ 0.7988056 ]
 [ 0.7018354 ]
 [ 0.88219285]
 [ 0.8416648 ]
 [ 0.9625032 ]
 [ 0

1300 Cost: 0.035559643 
Prediction:
 [[ 0.79203284]
 [ 0.81151986]
 [ 0.7663619 ]
 [ 0.81923276]
 [ 0.78214294]
 [ 0.7506887 ]
 [ 0.7865177 ]
 [ 0.7464098 ]
 [ 0.7299851 ]
 [ 0.7659956 ]
 [ 0.89931345]
 [ 0.59802544]
 [ 0.80100083]
 [ 0.65184593]
 [ 0.8778554 ]
 [ 0.7134141 ]
 [ 0.8819969 ]
 [ 0.81471086]
 [ 0.8113026 ]
 [ 0.76959693]
 [ 0.77124846]
 [ 0.7373972 ]
 [ 0.8038854 ]
 [ 0.85416085]
 [ 0.7120193 ]
 [ 0.8018725 ]
 [ 0.7871487 ]
 [ 0.8750466 ]
 [ 0.81851786]
 [ 0.7925055 ]
 [ 0.83785784]
 [ 0.65327287]
 [ 0.66149044]
 [ 0.67395246]
 [ 1.0023613 ]
 [ 0.89072436]
 [ 0.75739205]
 [ 0.90328807]
 [ 0.9212489 ]
 [ 0.57350576]
 [ 0.77500474]
 [ 0.6236392 ]
 [ 0.48707467]
 [ 0.4293784 ]
 [ 0.96033335]
 [ 0.8578751 ]
 [ 0.8998067 ]
 [ 0.59716487]
 [ 0.8930623 ]
 [ 1.0239508 ]
 [ 0.44175684]
 [ 0.6032121 ]
 [ 0.59316385]
 [ 0.74216723]
 [ 0.74576473]
 [ 1.0291023 ]
 [ 0.44655675]
 [ 0.67317295]
 [ 0.8222099 ]
 [ 0.77736104]
 [ 0.715646  ]
 [ 0.8390549 ]
 [ 0.8191354 ]
 [ 0.8998717 ]
 [ 

1700 Cost: 0.03069359 
Prediction:
 [[0.8146496 ]
 [0.8243903 ]
 [0.7922323 ]
 [0.84360456]
 [0.80832636]
 [0.7685243 ]
 [0.8133724 ]
 [0.77604663]
 [0.7624256 ]
 [0.79457116]
 [0.8885478 ]
 [0.6079628 ]
 [0.8139148 ]
 [0.6580212 ]
 [0.8873837 ]
 [0.704545  ]
 [0.9020432 ]
 [0.83529866]
 [0.81580794]
 [0.79658246]
 [0.79855883]
 [0.7602422 ]
 [0.7792715 ]
 [0.88229775]
 [0.71237534]
 [0.8121551 ]
 [0.7866653 ]
 [0.912681  ]
 [0.81395495]
 [0.7726517 ]
 [0.8181664 ]
 [0.66557026]
 [0.6542436 ]
 [0.6899494 ]
 [0.98555267]
 [0.87144935]
 [0.7770009 ]
 [0.8930732 ]
 [0.92516756]
 [0.58796144]
 [0.77833366]
 [0.6109482 ]
 [0.501251  ]
 [0.44514853]
 [0.92587626]
 [0.8456007 ]
 [0.8840543 ]
 [0.59745395]
 [0.88727164]
 [0.9898902 ]
 [0.45444646]
 [0.58504283]
 [0.59445065]
 [0.7353837 ]
 [0.74765694]
 [0.974668  ]
 [0.4585263 ]
 [0.66373384]
 [0.7997676 ]
 [0.7659613 ]
 [0.7260795 ]
 [0.81338227]
 [0.8065796 ]
 [0.8624494 ]
 [0.6044439 ]
 [0.78770363]
 [0.81011844]
 [0.7811713 ]
 [0.69734514

In [4]:
# Ask my score
print("1st life expectancy will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[1.23, 1.22, 0.41, 0.08, 0.33]]}))

print("2nd life expectancy will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[0.96, 1.24, 0.63, 0.11, 0.25]]}))



1st life expectancy will be  [[0.8839816]]
2nd life expectancy will be  [[0.6188247]]
